# Uncomment the next line to define a global platform for your project
# platform :ios, '16.0'

target 'TrainifyHub' do
 
use_frameworks!
  
  pod 'Firebase/Core'
  pod 'Firebase/Messaging'
  pod 'Firebase/Auth'
  pod 'Firebase/Firestore'
  pod 'Firebase/Storage'
  pod 'lottie-ios'

end
