apiVersion: apps/v1
kind: Deployment
metadata:
  name: messenger
  namespace: trainifyhub
  labels:
    app: messenger
spec:
  replicas: 1
  selector:
    matchLabels:
      app: messenger
  template:
    metadata:
      labels:
        app: messenger
    spec:
      containers:
        - name: messenger
          image: gregb884/messenger:v1
          imagePullPolicy: Always
          ports:
            - containerPort: 8084

          env:
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: trainifyhub-secret
                  key: DB_HOST
            - name: DB_NAME_MESSENGER
              valueFrom:
                secretKeyRef:
                  name: trainifyhub-secret
                  key: DB_NAME_MESSENGER
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: trainifyhub-secret
                  key: DB_USERNAME
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: trainifyhub-secret
                  key: DB_PASSWORD

            - name: JWT_JWK_SET_URI
              valueFrom:
                secretKeyRef:
                  name: trainifyhub-secret
                  key: JWT_JWK_SET_URI
            - name: JWT_ISSUER_URI
              valueFrom:
                secretKeyRef:
                  name: trainifyhub-secret
                  key: JWT_ISSUER_URI
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: trainifyhub-secret
                  key: JWT_SECRET

            - name: RABBITMQ_HOST
              valueFrom:
                secretKeyRef:
                  name: trainifyhub-secret
                  key: RABBITMQ_HOST
            - name: RABBITMQ_PORT
              valueFrom:
                secretKeyRef:
                  name: trainifyhub-secret
                  key: RABBITMQ_PORT
            - name: RABBITMQ_USERNAME
              valueFrom:
                secretKeyRef:
                  name: trainifyhub-secret
                  key: RABBITMQ_USERNAME
            - name: RABBITMQ_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: trainifyhub-secret
                  key: RABBITMQ_PASSWORD

            - name: EUREKA_DEFAULT_ZONE
              valueFrom:
                secretKeyRef:
                  name: trainifyhub-secret
                  key: EUREKA_DEFAULT_ZONE

          resources:
            requests:
              memory: "1Gi"
              cpu: "500m"
            limits:
              memory: "2Gi"
              cpu: "1000m"

---
apiVersion: v1
kind: Service
metadata:
  name: messenger-service
  namespace: trainifyhub
spec:
  selector:
    app: messenger
  ports:
    - protocol: TCP
      port: 8084
      targetPort: 8084
      nodePort: 30084
  type: NodePort