apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification
  namespace: trainifyhub
  labels:
    app: notification
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification
  template:
    metadata:
      labels:
        app: notification
    spec:
      containers:
        - name: messenger
          image: gregb884/notification:v1
          imagePullPolicy: Always
          ports:
            - containerPort: 8082

          env:
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: trainifyhub-secret
                  key: DB_HOST
            - name: DB_NAME_NOTIFICATION
              valueFrom:
                secretKeyRef:
                  name: trainifyhub-secret
                  key: DB_NAME_NOTIFICATION
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: trainifyhub-secret
                  key: DB_USERNAME
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: trainifyhub-secret
                  key: DB_PASSWORD

            - name: JWT_JWK_SET_URI
              valueFrom:
                secretKeyRef:
                  name: trainifyhub-secret
                  key: JWT_JWK_SET_URI
            - name: JWT_ISSUER_URI
              valueFrom:
                secretKeyRef:
                  name: trainifyhub-secret
                  key: JWT_ISSUER_URI
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: trainifyhub-secret
                  key: JWT_SECRET

            - name: RABBITMQ_HOST
              valueFrom:
                secretKeyRef:
                  name: trainifyhub-secret
                  key: RABBITMQ_HOST
            - name: RABBITMQ_PORT
              valueFrom:
                secretKeyRef:
                  name: trainifyhub-secret
                  key: RABBITMQ_PORT
            - name: RABBITMQ_USERNAME
              valueFrom:
                secretKeyRef:
                  name: trainifyhub-secret
                  key: RABBITMQ_USERNAME
            - name: RABBITMQ_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: trainifyhub-secret
                  key: RABBITMQ_PASSWORD

            - name: EUREKA_DEFAULT_ZONE
              valueFrom:
                secretKeyRef:
                  name: trainifyhub-secret
                  key: EUREKA_DEFAULT_ZONE

            - name: FIREBASE_KEY
              valueFrom:
                secretKeyRef:
                  name: trainifyhub-secret
                  key: FIREBASE_KEY

          resources:
            requests:
              memory: "1Gi"
              cpu: "500m"
            limits:
              memory: "2Gi"
              cpu: "1000m"

---
apiVersion: v1
kind: Service
metadata:
  name: notification-service
  namespace: trainifyhub
spec:
  selector:
    app: notification
  ports:
    - protocol: TCP
      port: 8082
      targetPort: 8082
      nodePort: 30082
  type: NodePort