apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: auth-service-monitor
  namespace: monitoring
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      io.kompose.service: auth-service
  namespaceSelector:
    matchNames:
      - workout-app
  endpoints:
    - port: "8080"
      interval: 30s
      path: /actuator/prometheus